version: '3.8'

services:
    classifiedsdb-instance: 
      image: postgres:18-alpine
      env_file: postgresql_db.env
      container_name: classifiedsdb-instance
      ports:
         - 5432:5432
      volumes:
         - postgresql-data:/var/lib/postgresql/18/data
         - ./classifieds_db.sql:/docker-entrypoint-initdb.d/classifieds_db.sql  # Auto-runs on startup
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U POSTGRES_USER -d POSTGRES_DB"]
         timeout: 10s
         retries: 5 
          
    classifiedsapi: 
      image: classifiedsapi.jar:latest
      env_file: classifieds_api.env
      container_name: classifieds-service
      build:
         context: .
         dockerfile: Dockerfile
      ports: 
         - 8080:8080
      links: 
         - classifiedsdb-instance
      depends_on: 
         - classifiedsdb-instance
volumes:
   postgresql-data:
      
      
      